<!doctype html>
<html lang="<?= $lang ?>">
    <head>
        <meta charset="<?= $charset ?>">
        <?= \DS\View::make('util.meta')->with(compact('meta')) ?>

        <base href="<?= $basePath ?>">

        <title><?= isset($title) ? $title . ' - ' . $mainTitle : $mainTitle ?></title>

        <?= \DS\View::make('util.stylesheets')->with(compact('stylesheets')) ?>
    </head>
    <body>
        <?= \DS\View::make('widget.navbar')->with($navbar) ?>

        <?= isset($flash) ? $flash : null ?>
        
        <?= isset($main) ? $main : null ?>

        <?= \DS\View::make('widget.footer') ?>

        <?= \DS\View::make('util.javascript')->with(compact('javascript')) ?>
    </body>
</html>