<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-push-1">
            <div class="alert alert-<?= $status ?> alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <p><?= $message ?></p>
            </div>
        </div>
    </div>
</div>