<footer>
    <div class="container">
        <div class="social">
            <a class="social-link github" href="https://github.com/DennisSkoko" target="_blank">
                <img src="img/icons/github.svg" alt="Github">
            </a>
            <a class="social-link instagram" href="https://www.instagram.com/dennisskoko/" target="_blank">
                <img src="img/icons/instagram.svg" alt="Instagram">
            </a>
        </div>
        <p><?= date('Y') ?> &copy; Dennis Skoko</p>
    </div>
</footer>