<nav class="navbar navbar-default navbar-static-top">
    <div class="container">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?= $brand["url"] ?>"><?= $brand["text"] ?></a>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <?php
                /** @var \Slim\Http\Uri $uri */
                $uri = \DS\DC::get('request')->getUri();
                $path = $uri->getPath();
                $path = $uri->getBasePath() . ($path === '/' ? $path : '/' . $path);

                foreach ($links as $text => $url): ?>

                    <?php if (!is_array($url)): ?>
                        <li class="<?= $path == $url ? 'active' : '' ?>"><a href="<?= $url ?>"><?= $text ?></a></li>
                    <?php else: ?>
                        <li class="dropdown <?= in_array($path, $url) ? 'active' : '' ?>">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?= $text ?> <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <?php foreach ($url as $subText => $subUrl): ?>
                                    <li class="<?= $path == $subUrl ? 'active' : '' ?>"><a href="<?= $subUrl ?>"><?= $subText ?></a></li>
                                <?php endforeach; ?>
                            </ul>
                        </li>
                    <?php endif; ?>

                <?php endforeach; ?>
            </ul>
        </div>

    </div>
</nav>