language: node_js
node_js:
  - "9"
  - "8"
cache:
  directories:
    - "client/node_modules"
    - "server/node_modules"
install:
  - cd client
  - npm install
  - cd ../server
  - npm install
  - cd ..
script:
  - cd client
  - npm run lint
  - cd ../server
  - npm run lint
