service: website

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: ${self:resources.Resources.WebAssets.Properties.BucketName}
      localDir: build

provider:
  name: aws
  region: ${opt:region, 'eu-north-1'}
  stage: prod

resources:
  Resources:
    WebAssets:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: www.dennisskoko.com
        WebsiteConfiguration:
          IndexDocument: index.html

    WebAssetsPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref WebAssets
        PolicyDocument:
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource: !Join ['', [!GetAtt WebAssets.Arn, '/*']]
              Principal: '*'
