<main class="container">
    <div class="row">
        <div class="col-lg-6 col-lg-push-3">
            <form method="post">
                <div class="form-group form-group-lg">
                    <input class="form-control" type="email" name="email" placeholder="Email" required>
                </div>

                <div class="form-group form-group-lg">
                    <input class="form-control" name="subject" placeholder="Subject" required>
                </div>

                <div class="form-group form-group-lg">
                    <textarea class="form-control" name="message" placeholder="Message" rows="4"></textarea>
                </div>

                <input type="submit" class="btn btn-lg btn-block btn-default" value="Send">
            </form>
        </div>
    </div>
</main>