<main>
    <div class="jumbotron">
        <div class="container">
            <h2>Welcome!</h2>
            <p>Hi, my name is Dennis Skoko and this will be my website where I showoff all of my skills.</p>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-push-2">
                <article>
                    <?= $content ?>
                </article>
            </div>
        </div>
    </div>
</main>