<main>
    <div class="jumbotron">
        <div class="container">
            <?= $intro ?>
            <div class="btn-group">
                <a class="btn btn-default btn-lg" href="https://github.com/DennisSkoko" target="_blank">Github</a>
                <a class="btn btn-primary btn-lg" href="<?= \DS\DC::get('router')->pathFor('projects') ?>">Projects</a>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-push-3">
                <article>
                    <?= $content ?>
                </article>
            </div>
        </div>
    </div>
</main>